name: CI

on:
  push:
    branches: ["main"]

jobs:
  rust:
    name: Rust checks
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --all-features

      - name: Test
        run: cargo test --all-features
